### PR TITLE
Request to talk

### PR DESCRIPTION
**Pull request by hashkash**

### CODE REVIEW

**Comment by hashkash** [comment]
Hey,

Any update on this?

Cheers,

Kash

**Comment by franziskuskiefer** [comment]
@hannob, @mozfreddyb wdyt? The suggested topic is a little less web-based than usually but still interesting imho.

**Comment by mozfreddyb** [comment]
That sounds fun! Let me figure out scheduling options…

**Comment by hashkash** [comment]
Awesome :)

**Comment by hannob** [comment]
@hashkash could you do the talk on December 3rd?

**Comment by hashkash** [comment]
Hey Hanno,

Sure, I can do that!

**Comment by hashkash** [comment]
Heho,
Is it okay if the talk tends towards an academic style?
Also, is it confirmed so that I can make necessary preparations? :)

**Comment by hannob** [comment]
Feel free.

I'll announce it later today, so consider it as confirmed.

**Comment by hannob** [comment]
we don't really use the json format any more, but I added it to the html

**Pull request closed without merging**
